import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/ui/Navbar/Navbar";

// Load Helvetica Now Display fonts with different weights
const helveticaNowDisplay = localFont({
  src: [
    {
      path: "./fonts/HelveticaNowDisplay-BoldIta.woff2",
      weight: "bold",
      style: "italic",
    },
    {
      path: "./fonts/HelveticaNowDisplay-BoldIta.woff",
      weight: "bold",
      style: "italic",
    },
    {
      path: "./fonts/HelveticaNowDisplay-BlackIta.woff2",
      weight: "900",
      style: "italic",
    },
    {
      path: "./fonts/HelveticaNowDisplay-BlackIta.woff",
      weight: "900",
      style: "italic",
    },
    {
      path: "./fonts/HelveticaNowDisplay-ExtBlk.woff2",
      weight: "900",
      style: "normal",
    },
    {
      path: "./fonts/HelveticaNowDisplay-ExtBlk.woff",
      weight: "900",
      style: "normal",
    },
    {
      path: "./fonts/HelveticaNowDisplay-Black.woff2",
      weight: "900",
      style: "normal",
    },
    {
      path: "./fonts/HelveticaNowDisplay-Black.woff",
      weight: "900",
      style: "normal",
    },
    {
      path: "./fonts/HelveticaNowDisplay-Bold.woff2",
      weight: "bold",
      style: "normal",
    },
    {
      path: "./fonts/HelveticaNowDisplay-Bold.woff",
      weight: "bold",
      style: "normal",
    },
    {
      path: "./fonts/HelveticaNowDisplay-ExtBdIta.woff2",
      weight: "900",
      style: "italic",
    },
    {
      path: "./fonts/HelveticaNowDisplay-ExtBdIta.woff",
      weight: "900",
      style: "italic",
    },
    {
      path: "./fonts/HelveticaNowDisplay-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/HelveticaNowDisplay-Light.woff",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/HelveticaNowDisplay-LightIta.woff2",
      weight: "300",
      style: "italic",
    },
    {
      path: "./fonts/HelveticaNowDisplay-LightIta.woff",
      weight: "300",
      style: "italic",
    },
    {
      path: "./fonts/HelveticaNowDisplay-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/HelveticaNowDisplay-Medium.woff",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/HelveticaNowDisplay-MedIta.woff2",
      weight: "500",
      style: "italic",
    },
    {
      path: "./fonts/HelveticaNowDisplay-MedIta.woff",
      weight: "500",
      style: "italic",
    },
    {
      path: "./fonts/HelveticaNowDisplay-ExtLtIta.woff2",
      weight: "300",
      style: "italic",
    },
    {
      path: "./fonts/HelveticaNowDisplay-ExtLtIta.woff",
      weight: "300",
      style: "italic",
    },
    {
      path: "./fonts/HelveticaNowDisplay-RegIta.woff2",
      weight: "normal",
      style: "italic",
    },
    {
      path: "./fonts/HelveticaNowDisplay-RegIta.woff",
      weight: "normal",
      style: "italic",
    },
    {
      path: "./fonts/HelveticaNowDisplay-ExtLt.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/HelveticaNowDisplay-ExtLt.woff",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/HelveticaNowDisplay-ExtBlkIta.woff2",
      weight: "900",
      style: "italic",
    },
    {
      path: "./fonts/HelveticaNowDisplay-ExtBlkIta.woff",
      weight: "900",
      style: "italic",
    },
    {
      path: "./fonts/HelveticaNowDisplay-ExtraBold.woff2",
      weight: "bold",
      style: "normal",
    },
    {
      path: "./fonts/HelveticaNowDisplay-ExtraBold.woff",
      weight: "bold",
      style: "normal",
    },
    {
      path: "./fonts/HelveticaNowDisplay-Regular.woff2",
      weight: "normal",
      style: "normal",
    },
    {
      path: "./fonts/HelveticaNowDisplay-Regular.woff",
      weight: "normal",
      style: "normal",
    },
    {
      path: "./fonts/HelveticaNowDisplay-ThinIta.woff2",
      weight: "100",
      style: "italic",
    },
    {
      path: "./fonts/HelveticaNowDisplay-ThinIta.woff",
      weight: "100",
      style: "italic",
    },
    {
      path: "./fonts/HelveticaNowDisplay-Thin.woff2",
      weight: "100",
      style: "normal",
    },
    {
      path: "./fonts/HelveticaNowDisplay-Thin.woff",
      weight: "100",
      style: "normal",
    },
  ],
  variable: "--font-helvetica-now-display", // Create a CSS variable for the font
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${helveticaNowDisplay.variable} antialiased`}>
        <header>
          <Navbar />
        </header>
        {children}
      </body>
    </html>
  );
}
